higan.components += z80

higan.objects += higan-spec-interface  higan-spec-keyboard higan-spec-expansion higan-spec-system
higan.objects += higan-spec-cpu higan-spec-ula
higan.objects += higan-spec-snapshot

$(object.path)/higan-spec-interface.o:  $(higan.path)/spec/interface/interface.cpp
$(object.path)/higan-spec-keyboard.o:   $(higan.path)/spec/keyboard/keyboard.cpp
$(object.path)/higan-spec-expansion.o:  $(higan.path)/spec/expansion/expansion.cpp
$(object.path)/higan-spec-system.o:     $(higan.path)/spec/system/system.cpp
$(object.path)/higan-spec-cpu.o:        $(higan.path)/spec/cpu/cpu.cpp
$(object.path)/higan-spec-ula.o:        $(higan.path)/spec/ula/ula.cpp
$(object.path)/higan-spec-snapshot.o:   $(higan.path)/spec/snapshot/snapshot.cpp